### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by kubosho** [kubosho/Nico#15]
## Required

- [x] コードベースを https://github.com/windyakin/Honoka のmasterにする
- [x] Honokaと書かれているところをNicoにする
     - [x] README
     - [x] bower.json
     - [x] package.json
     - [x] gulpfile.js
     - [x] docs/ 以下
     - [x] dist/ 以下
- [x] LicenseにNicoの分も追加
- [x] 配色をにこっぽくする
     - #f3d4df, #ff50ac, #ff92cb
- [x] バージョン番号を統一する
     - https://github.com/windyakin/Honoka/issues/12 を参考にする

### after Pull Request merged

- [x] npm publish
- [x] GitHub Pagesのsourcesを `docs/` へ変更
- [x] gh-pages branch削除
- [x] Release textの執筆

## Nice to have

- [ ] example用のファイルを `docs/` 以下へ出力するスクリプト作成
    - [deploy-to-gh-pages.sh](https://github.com/kubosho/Nico/blob/ccba36ee6ef4363405f3bf9669ab05ae9af1c0c9/.bin/deploy-to-gh-pages.sh) を参考にする

**Comment by kubosho** [comment]
作業中: https://github.com/kubosho/Nico/tree/v4

**Comment by kubosho** [comment]
完
